# -*- coding: utf-8 -*-
"""Project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Ubea7IwYpdyWNY9zQVAeBx69slSe210

# NumPy: The Number Cruncher

# Project: Student Grade Analyzer
"""

# Project 1 : Numpy -

import numpy as np


np.random.seed(42)   # makes output reproducible

scores = np.random.randint(0, 101, size=50)

print(scores)

print(np.mean(scores))

print(np.median(scores))

print(np.max(scores))

print(np.min(scores))

print(np.std(scores))

print("25th Percentile:", np.percentile(scores, 25))
print("50th Percentile:", np.percentile(scores, 50))
print("75th Percentile:", np.percentile(scores, 75))

# Score

fail_students = scores[scores < 40]

print(fail_students)

# Index

fail_indexes = np.where(scores < 40)

print(fail_indexes)

distinction = scores[scores > 85]

print(distinction)

distinction_indexes = np.where(scores > 85)

print(distinction_indexes)

# Normalized Score:

normalized_scores = (scores - np.min(scores)) / (np.max(scores) - np.min(scores))

print(normalized_scores)

# Reshape :

reshaped_scores = scores.reshape(5, 10)

print(reshaped_scores)

# Row Wise Average :

subject_average = np.mean(reshaped_scores, axis=1)

print(subject_average)

# Column Wise Average :

student_average = np.mean(reshaped_scores, axis=0)

print(student_average)

# Sorting Score:

sorted_scores = np.sort(scores)

print(sorted_scores)

"""# NumPy: Image as a Matrix

# Project: Grayscale Image Manipulator

"""

pip install numpy matplotlib pillow

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = mpimg.imread("/content/josh-williams-TQ-U4B9c_jw-unsplash.jpg")

print(img)

print(img.shape)

plt.imshow(img)
plt.title("Original Image")
plt.axis("off")
plt.show()

gray = np.mean(img, axis=2)

print(gray)
print(gray.shape)

bright = np.clip(img + 50, 0, 255)

plt.imshow(bright.astype(np.uint8))
plt.title("Brightened")
plt.axis("off")
plt.show()

dark = np.clip(img - 50, 0, 255)

plt.imshow(dark.astype(np.uint8))
plt.title("Darkened")
plt.axis("off")
plt.show()

rotated = np.rot90(img)

plt.imshow(rotated)
plt.title("Rotated")
plt.axis("off")
plt.show()

print(np.mean(img))

print(np.max(img))

print(np.min(img))