# -*- coding: utf-8 -*-
"""Project 5.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJW1YCD_zhiwCneidrIGdRWsgjcjqy1G

# Pandas: Merging & Reshaping Data

# Project: E-Commerce Order Intelligence
"""

pip install pandas

import pandas as pd
import numpy as np

orders = pd.read_csv("/content/olist_orders_dataset.csv")
customers = pd.read_csv("/content/olist_customers_dataset.csv")
items = pd.read_csv("/content/olist_order_items_dataset.csv")
products = pd.read_csv("/content/olist_products_dataset.csv")

print(orders.shape)
print(customers.shape)
print(items.shape)
print(products.shape)

print(orders.columns)
print(customers.columns)
print(items.columns)
print(products.columns)

orders.head()

orders_customers = pd.merge(
    orders,
    customers,
    on="customer_id",
    how="inner"
)

orders_customers.head()

master_df = orders.merge(
    customers,
    on="customer_id"
).merge(
    items,
    on="order_id"
).merge(
    products,
    on="product_id",
    how="left"
)

master_df.head()

customer_revenue = master_df.groupby(
    "customer_unique_id"
)["price"].sum().sort_values(
    ascending=False
)

print(customer_revenue.head(10))

top_categories = master_df.groupby(
    "product_category_name"
)["price"].sum().sort_values(
    ascending=False
)

print(top_categories.head(10))

state_orders = master_df["customer_state"].value_counts()

print(state_orders)

master_df["order_purchase_timestamp"] = pd.to_datetime(
    master_df["order_purchase_timestamp"]
)

master_df["Year"] = master_df[
    "order_purchase_timestamp"
].dt.year

master_df["Month"] = master_df[
    "order_purchase_timestamp"
].dt.month

print(master_df[["Year", "Month"]].head())

monthly_sales = master_df.groupby(
    ["Year", "Month"]
)["price"].sum()

print(monthly_sales)

customer_orders = master_df.groupby(
    "customer_unique_id"
)["order_id"].nunique()

one_order = customer_orders[
    customer_orders == 1
]

print(one_order.head())

avg_order = master_df.groupby(
    "order_id"
)["price"].sum().mean()

print(avg_order)

master_df["order_delivered_customer_date"] = pd.to_datetime(
    master_df["order_delivered_customer_date"]
)

master_df["delivery_days"] = (
    master_df["order_delivered_customer_date"] -
    master_df["order_purchase_timestamp"]
).dt.days

print(master_df["delivery_days"].head())

slow_cities = master_df.groupby(
    "customer_city"
)["delivery_days"].mean().sort_values(
    ascending=False
)

print(slow_cities.head(10))

expensive_products = master_df.groupby(
    "product_category_name"
)["price"].mean().sort_values(
    ascending=False
)

print(expensive_products.head(10))

top_customers = master_df.groupby(
    "customer_unique_id"
)["order_id"].nunique().sort_values(
    ascending=False
)

print(top_customers.head(10))

top_customers = master_df.groupby(
    "customer_unique_id"
)["order_id"].nunique().sort_values(
    ascending=False
)

print(top_customers.head(10))