# -*- coding: utf-8 -*-
"""Project 3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EE3v736U87-yp5Kv5f0CrOLdB-_xJ_DH

# Pandas: Your First DataFrame

# Project: IPL Match Data Explorer
"""

pip install pandas

import pandas as pd

df = pd.read_csv("matches.csv")

df.head()

df.tail()

df.info()

df.describe()

print(df.columns)

print(df.shape)

matches_per_season = df["season"].value_counts()

print(matches_per_season)

most_wins = df["winner"].value_counts()

print(most_wins)

venue_matches = df[df["venue"] == "Wankhede Stadium"]

print(venue_matches)

top_players = df["player_of_match"].value_counts().head(5)

print(top_players)

print(df.isnull().sum())

mi_matches = df[df["winner"] == "Mumbai Indians"]

print(mi_matches)

print(df["team1"].nunique())

field_first = df[df["win_by_wickets"] > 0]

print(field_first["winner"].value_counts())

print(df[["season", "winner", "venue"]])

print(df.loc[0])

print(df.iloc[0])