# -*- coding: utf-8 -*-
"""Project 4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jr9xYMswJU1xaT2cmIgOhZrzwef_L6kf

# Pandas: GroupBy & Aggregation

# Project: Sales Performance Dashboard (Data Layer)
"""

pip install pandas

import pandas as pd
import numpy as np

df = pd.read_csv("/content/Superstore.csv", encoding="ISO-8859-1")

df.head()

df.info()

print(df.columns)

print(df.shape)

sales_by_region = df.groupby("Region")["Sales"].sum()

print(sales_by_region)

profit_by_region = df.groupby("Region")["Profit"].sum()

print(profit_by_region)

region_category = df.groupby(
    ["Region", "Category"]
)[["Sales", "Profit"]].sum()

print(region_category)

summary = df.groupby(
    ["Region", "Category"]
).agg({
    "Sales": ["sum", "mean", "max"],
    "Profit": ["sum", "mean", "min"]
})

print(summary)

summary = summary.reset_index()

print(summary)

subcat_sales = df.groupby(
    ["Region", "Sub-Category"]
)["Sales"].sum().reset_index()

subcat_sales = subcat_sales.sort_values(
    ["Region", "Sales"],
    ascending=[True, False]
)

top3 = subcat_sales.groupby("Region").head(3)

print(top3)

df["Profit Margin %"] = (
    df["Profit"] / df["Sales"]
) * 100

print(df.head())

df["Profit Margin %"] = df[
    "Profit Margin %"
].round(2)

df["Sales Category"] = df["Sales"].apply(
    lambda x: "High" if x > 500 else "Low"
)

print(df[["Sales", "Sales Category"]].head())

pivot = pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Segment",
    aggfunc="mean"
)

print(pivot)

pivot2 = pd.pivot_table(
    df,
    values=["Sales", "Profit"],
    index="Region",
    columns="Segment",
    aggfunc=["mean", "sum"]
)

print(pivot2)

loss_df = df[df["Profit"] < 0]

print(loss_df.head())

df["Order Date"] = pd.to_datetime(
    df["Order Date"]
)

print(df["Order Date"].dtype)

top_profit = df.sort_values(
    by="Profit",
    ascending=False
)

print(top_profit.head())

best_products = df.groupby(
    "Product Name"
)["Sales"].sum().sort_values(
    ascending=False
)

print(best_products.head(10))

orders = df.groupby("Region").size()

print(orders)

avg_profit = df.groupby(
    "Category"
)["Profit"].mean()

print(avg_profit)

df["Region Avg Sales"] = df.groupby(
    "Region"
)["Sales"].transform("mean")

print(df.head())

high_profit = df[
    df["Profit"] > df["Profit"].mean()
]

print(high_profit.head())