# -*- coding: utf-8 -*-
"""Student.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nA6vvR_9J7HBE4jyNZzRTYZ8nGHPsRaL
"""

# shape of the data we got

| ID | Marks | Hours Studied | Attendance |
| -- | ----- | ------------- | ---------- |
| 1  | 85    | 5             | 90         |
| 2  | 78    | 4             | 85         |
| 3  | 92    | 6             | 95         |
| 4  | 60    | 2             | 70         |
| 5  | 75    | 3             | 80         |

import numpy as np
data = np.array([
    [1,85,5,90],
    [2,78,4,85],
    [3,92,6,95],
    [4,60,2,70],
    [5,75,3,80]
])

print(data.shape)

print(data[0])      # row
print(data[:,1])    # Column
print(data[1:4])    # Specific (value matrix)

data[:,1] = data[:,1] + 5

print(data)

print(np.mean(data[:,1]))
print(np.max(data[:,1]))
print(np.std(data[:,1]))
print(np.median(data[:,1]))
print(np.min(data[:,1]))

high_scores = data[data[:,1] > 80]
print(high_scores)

marks = data[:,1]

print(marks.reshape(5,1))

import pandas as pd
df = pd.DataFrame(data, columns=['ID','Marks','Hours Studied','Attendance'])
print(df)

a = data[:,1]
print(a)
print(type(a))
data[:,1]

df["Marks"]

print(df.head())

print(df.info())

print(df.describe())

df.head()      # First 5 rows
df.tail()      # Last 5 rows
df.shape       # (rows, columns)
df.columns     # Column names
df.info()      # Summary
df.describe()  # Statistics

df["Performance"] = df["Marks"] > 80
print(df)

sorted_df = df.sort_values(by="Marks", ascending=False)
print(sorted_df)

df.loc[2,"Marks"] = None
print(df)

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

df["Category"] = ["A", "B","C","D","E"]
print(df)

print(df.groupby("Category")["Marks"].mean())

df = pd.DataFrame({
    "date" : ["2024-01-15", ""]
})